# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-22 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
